name: CI-CD Pipeline
on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo code
      - uses: actions/checkout@v3

      # set up python

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      #Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Set up Docker buildx

      - name: Set up Docker Buildx
        uses : docker/setup-buildx-action@v2
        


